# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Félix-Antoine Dion
tagline:          à la recherche de la panacée
url:              http://felix-antoine-dion.github.io
paginate:         1
baseurl:          /
author:
  name:           Félix-Antoine Dopm
  url:            http://ca.linkedin.com/in/felixantoinedion
  email:          felix.antoine.dion@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/felix-antoine-dion/felix-antoine-dion.github.io
